name: Build Unsigned iOS IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clean
        run: flutter clean

      - name: Get packages
        run: flutter pub get

      - name: Install Pods
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign --config-only
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos -destination generic/platform=iOS -derivedDataPath ../build/ios build CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" DEVELOPMENT_TEAM="" COMPILER_INDEX_STORE_ENABLE=NO

      - name: Make IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/Build/Products/Release-iphoneos/Runner.app Payload/
          zip -r app.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: app.ipa
